### ISSUE TITLE
Django 1.7 compatibility

### ISSUE THREAD

**Issue by zanklord** [sunlightlabs/django-secretballot#19]
/home/zanklord/programas/python/hearthstone/webapp/secretballot/__init__.py:48: RemovedInDjango18Warning: `VotableManager.get_query_set` method should be renamed `get_queryset`.
  class VotableManager(base_manager):

solved renaming "def get_query_set(self):" to "def get_queryset(self):"

**Comment by jamesturk** [comment]
this and other things fixed in current 0.4.x work, just merged into master, release incoming
